---
 - name: gather instance facts
   ec2_snapshot_info:
     region: "{{ usregion }}"
   register: snapshot_output

 - name: Debug statement
   debug:
     msg: "{{ snapshot_output }}"
 
 - name: get instance list to add tags
   set_fact:
     instancelist: "{{snapshot_output.snapshots | map(attribute='snapshot_id') | list }}"

 - name: Ensure snapshot tags are present on a resource
   ec2_tag:
    region: "{{ usregion }}"
    resource: "{{ item }}"
    state: present
    tags:
      project: infra
      env: dev
    #aws_access_key: "{{ accesskey }}"
    #aws_secret_key: "{{ secretkey }}"
   with_items: "{{ instancelist }}"
