---
# tasks file for terminate_ec2
 - name: Terminate instances that were previously created
   ec2:
    state: absent
    instance_ids: "{{ instanceid }}"
    region: "{{ region }}"
    aws_access_key: "{{ accesskey }}"
    aws_secret_key: "{{ secretkey }}"


